GET http://localhost:8080/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJBRE1JTiIsIlVTRVIiXSwic3ViIjoibGFjaGV6YXIuYmFsZXZAZ21haWwuY29tIiwiaWF0IjoxNzEyNDcwNTA3LCJuYmYiOjE3MTI0NzA1MDcsImV4cCI6MTcxMjQ3NDEwN30.AboOQxc31YImrnR1-5LCkz6LWHh0GGQ8GUW426PeoWw