spring.application.name: client
server.port: 9001

jwt:
  secret: N2NuZ0NIM0FZbWpReTJ4Tzc1WHdTRWJNaFBOajdYTUQ=
  expiration: 6000000

logging:
  level:
    org.springframework.security: TRACE
    java:
      net:
        http: TRACE